### ISSUE TITLE
Out of date?

### ISSUE THREAD

**Issue by apedance** [PolitoInc/DNS-ELK#1]
I only get very big "messages" instead of reports being visually splitted into BLOCK, FORWARD,...
Any plan to update this in the future?

**Comment by mallware** [comment]
Hi @apedance thanks for the feedback. Yes, depending on what Pi-hole version you are using, the grok patterns and configs may be broken. Pi-hole 4.x changed how logging and lots of of other features work so I likely need to update the regexes and ELK configs. This is on the roadmap, just need some spare time to fix everything.

**Comment by q2dg** [comment]
Well, it seems https://github.com/nin9s/elk-hole is better maintained. Let's move on

**Comment by fmast** [comment]
updated, give it a try?
